default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: <%= ENV.fetch("DEVELOPMENT_DATABASE", "db/development.sqlite3") %>

test:
  <<: *default
<% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV.fetch("DATABASE_URL") %>
<% else %>
  adapter: sqlite3
  database: <%= ENV.fetch("TEST_DATABASE", "db/test.sqlite3") %>
<% end %>

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  prepared_statements: true
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_STATEMENT_TIMEOUT", "5000") %>
